name: Setup new project on Stepman.AI 

on:
  create:
  workflow_dispatch:

jobs:
  generate-project:
    if: >-
      ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_KEY }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Generate project from stepmanai/project_template
        run: |
          copier copy --vcs-ref main \
            --data project_name="${{ github.event.repository.name }}" \
            --data project_description="${{ github.event.description }}" \
          https://github.com/stepmanai/base-template.git .

      - name: Commit to main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Initializing ${{ github.event.repository.name }} project with Copier template."
          create_branch: false
