name: Setup new project on Stepman.AI

on:
  workflow_dispatch:

jobs:
  generate-project:
    if: >-
      ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out template repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_KEY }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Check object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - name: Generate project from gh:stepmanai/project_template
        run: |
          copier copy --vcs-ref main \
            --data project_name="${{ github.event.repository.name }}" \
            --data project_description="${{ github.event.description }}" \
          https://github.com/stepmanai/base-template.git .

      - name: Create uv.lock file
        run: |
          make install

      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run -a

      - name: Commit to main branch with formatted changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Initializing ${{ github.event.repository.name }} project with Copier template."
          create_branch: false
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
