name: Setup new project on Stepman.AI 

on:
  create:
  workflow_dispatch:

jobs:
  generate-project:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_KEY }}


      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Generate project from stepmanai/project_template
        run: |
          copier copy --vcs-ref main \
            --data project_name="${{ github.event.repository.name }}" \
            --data project_description="${{ github.event.description }}" \
          https://github.com/stepmanai/base-template.git .
