name: Setup new project on Stepman.AI 

on:
  create:

jobs:
  generate-project:
    runs-on: ubuntu-latest
    steps:

      - name: Setup SSH Keys and known_hosts
        uses: webfactory/ssh-agent@v0.9.0

      - name: Check out
        uses: actions/checkout@v4


      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Generate project from stepmanai/project_template
        run: |
          copier copy --vcs-ref main \
            --data project_name="${{ github.event.repository.name }}" \
            --data project_description="${{ github.event.description }}" \
          git@github.com:stepmanai/base_template.git .
